/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as ApiVoteRouteImport } from './routes/api/vote'
import { Route as ApiSuggestionsRouteImport } from './routes/api/suggestions'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiDocumentRouteImport } from './routes/api/document'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiFilesUploadRouteImport } from './routes/api/files.upload'
import { Route as ApiChatIdStreamRouteImport } from './routes/api/chat_.$id.stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoteRoute = ApiVoteRouteImport.update({
  id: '/api/vote',
  path: '/api/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestionsRoute = ApiSuggestionsRouteImport.update({
  id: '/api/suggestions',
  path: '/api/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentRoute = ApiDocumentRouteImport.update({
  id: '/api/document',
  path: '/api/document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRoute = ApiFilesUploadRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIdStreamRoute = ApiChatIdStreamRouteImport.update({
  id: '/api/chat_/$id/stream',
  path: '/api/chat/$id/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/document': typeof ApiDocumentRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/api/vote': typeof ApiVoteRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat': typeof ChatIndexRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/chat/$id/stream': typeof ApiChatIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/document': typeof ApiDocumentRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/api/vote': typeof ApiVoteRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat': typeof ChatIndexRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/chat/$id/stream': typeof ApiChatIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/document': typeof ApiDocumentRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/api/vote': typeof ApiVoteRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/chat_/$id/stream': typeof ApiChatIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/document'
    | '/api/history'
    | '/api/suggestions'
    | '/api/vote'
    | '/chat/$id'
    | '/chat'
    | '/api/files/upload'
    | '/api/chat/$id/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/document'
    | '/api/history'
    | '/api/suggestions'
    | '/api/vote'
    | '/chat/$id'
    | '/chat'
    | '/api/files/upload'
    | '/api/chat/$id/stream'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/document'
    | '/api/history'
    | '/api/suggestions'
    | '/api/vote'
    | '/chat/$id'
    | '/chat/'
    | '/api/files/upload'
    | '/api/chat_/$id/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDocumentRoute: typeof ApiDocumentRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiSuggestionsRoute: typeof ApiSuggestionsRoute
  ApiVoteRoute: typeof ApiVoteRoute
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiFilesUploadRoute: typeof ApiFilesUploadRoute
  ApiChatIdStreamRoute: typeof ApiChatIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vote': {
      id: '/api/vote'
      path: '/api/vote'
      fullPath: '/api/vote'
      preLoaderRoute: typeof ApiVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggestions': {
      id: '/api/suggestions'
      path: '/api/suggestions'
      fullPath: '/api/suggestions'
      preLoaderRoute: typeof ApiSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document': {
      id: '/api/document'
      path: '/api/document'
      fullPath: '/api/document'
      preLoaderRoute: typeof ApiDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat_/$id/stream': {
      id: '/api/chat_/$id/stream'
      path: '/api/chat/$id/stream'
      fullPath: '/api/chat/$id/stream'
      preLoaderRoute: typeof ApiChatIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDocumentRoute: ApiDocumentRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiSuggestionsRoute: ApiSuggestionsRoute,
  ApiVoteRoute: ApiVoteRoute,
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiFilesUploadRoute: ApiFilesUploadRoute,
  ApiChatIdStreamRoute: ApiChatIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
