/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as ChatApiVoteRouteImport } from './routes/chat/api/vote'
import { Route as ChatApiSuggestionsRouteImport } from './routes/chat/api/suggestions'
import { Route as ChatApiHistoryRouteImport } from './routes/chat/api/history'
import { Route as ChatApiDocumentRouteImport } from './routes/chat/api/document'
import { Route as ChatApiChatRouteImport } from './routes/chat/api/chat'
import { Route as ChatApiFilesUploadRouteImport } from './routes/chat/api/files.upload'
import { Route as ChatApiChatIdStreamRouteImport } from './routes/chat/api/chat_.$id.stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatApiVoteRoute = ChatApiVoteRouteImport.update({
  id: '/chat/api/vote',
  path: '/chat/api/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatApiSuggestionsRoute = ChatApiSuggestionsRouteImport.update({
  id: '/chat/api/suggestions',
  path: '/chat/api/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatApiHistoryRoute = ChatApiHistoryRouteImport.update({
  id: '/chat/api/history',
  path: '/chat/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatApiDocumentRoute = ChatApiDocumentRouteImport.update({
  id: '/chat/api/document',
  path: '/chat/api/document',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatApiChatRoute = ChatApiChatRouteImport.update({
  id: '/chat/api/chat',
  path: '/chat/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatApiFilesUploadRoute = ChatApiFilesUploadRouteImport.update({
  id: '/chat/api/files/upload',
  path: '/chat/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatApiChatIdStreamRoute = ChatApiChatIdStreamRouteImport.update({
  id: '/chat/api/chat_/$id/stream',
  path: '/chat/api/chat/$id/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat': typeof ChatIndexRoute
  '/chat/api/chat': typeof ChatApiChatRoute
  '/chat/api/document': typeof ChatApiDocumentRoute
  '/chat/api/history': typeof ChatApiHistoryRoute
  '/chat/api/suggestions': typeof ChatApiSuggestionsRoute
  '/chat/api/vote': typeof ChatApiVoteRoute
  '/chat/api/files/upload': typeof ChatApiFilesUploadRoute
  '/chat/api/chat/$id/stream': typeof ChatApiChatIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat': typeof ChatIndexRoute
  '/chat/api/chat': typeof ChatApiChatRoute
  '/chat/api/document': typeof ChatApiDocumentRoute
  '/chat/api/history': typeof ChatApiHistoryRoute
  '/chat/api/suggestions': typeof ChatApiSuggestionsRoute
  '/chat/api/vote': typeof ChatApiVoteRoute
  '/chat/api/files/upload': typeof ChatApiFilesUploadRoute
  '/chat/api/chat/$id/stream': typeof ChatApiChatIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/chat/$id': typeof ChatIdRoute
  '/chat/': typeof ChatIndexRoute
  '/chat/api/chat': typeof ChatApiChatRoute
  '/chat/api/document': typeof ChatApiDocumentRoute
  '/chat/api/history': typeof ChatApiHistoryRoute
  '/chat/api/suggestions': typeof ChatApiSuggestionsRoute
  '/chat/api/vote': typeof ChatApiVoteRoute
  '/chat/api/files/upload': typeof ChatApiFilesUploadRoute
  '/chat/api/chat_/$id/stream': typeof ChatApiChatIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/chat/$id'
    | '/chat'
    | '/chat/api/chat'
    | '/chat/api/document'
    | '/chat/api/history'
    | '/chat/api/suggestions'
    | '/chat/api/vote'
    | '/chat/api/files/upload'
    | '/chat/api/chat/$id/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/chat/$id'
    | '/chat'
    | '/chat/api/chat'
    | '/chat/api/document'
    | '/chat/api/history'
    | '/chat/api/suggestions'
    | '/chat/api/vote'
    | '/chat/api/files/upload'
    | '/chat/api/chat/$id/stream'
  id:
    | '__root__'
    | '/'
    | '/auth/sign-in'
    | '/chat/$id'
    | '/chat/'
    | '/chat/api/chat'
    | '/chat/api/document'
    | '/chat/api/history'
    | '/chat/api/suggestions'
    | '/chat/api/vote'
    | '/chat/api/files/upload'
    | '/chat/api/chat_/$id/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatApiChatRoute: typeof ChatApiChatRoute
  ChatApiDocumentRoute: typeof ChatApiDocumentRoute
  ChatApiHistoryRoute: typeof ChatApiHistoryRoute
  ChatApiSuggestionsRoute: typeof ChatApiSuggestionsRoute
  ChatApiVoteRoute: typeof ChatApiVoteRoute
  ChatApiFilesUploadRoute: typeof ChatApiFilesUploadRoute
  ChatApiChatIdStreamRoute: typeof ChatApiChatIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/api/vote': {
      id: '/chat/api/vote'
      path: '/chat/api/vote'
      fullPath: '/chat/api/vote'
      preLoaderRoute: typeof ChatApiVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/api/suggestions': {
      id: '/chat/api/suggestions'
      path: '/chat/api/suggestions'
      fullPath: '/chat/api/suggestions'
      preLoaderRoute: typeof ChatApiSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/api/history': {
      id: '/chat/api/history'
      path: '/chat/api/history'
      fullPath: '/chat/api/history'
      preLoaderRoute: typeof ChatApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/api/document': {
      id: '/chat/api/document'
      path: '/chat/api/document'
      fullPath: '/chat/api/document'
      preLoaderRoute: typeof ChatApiDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/api/chat': {
      id: '/chat/api/chat'
      path: '/chat/api/chat'
      fullPath: '/chat/api/chat'
      preLoaderRoute: typeof ChatApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/api/files/upload': {
      id: '/chat/api/files/upload'
      path: '/chat/api/files/upload'
      fullPath: '/chat/api/files/upload'
      preLoaderRoute: typeof ChatApiFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/api/chat_/$id/stream': {
      id: '/chat/api/chat_/$id/stream'
      path: '/chat/api/chat/$id/stream'
      fullPath: '/chat/api/chat/$id/stream'
      preLoaderRoute: typeof ChatApiChatIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSignInRoute: AuthSignInRoute,
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatApiChatRoute: ChatApiChatRoute,
  ChatApiDocumentRoute: ChatApiDocumentRoute,
  ChatApiHistoryRoute: ChatApiHistoryRoute,
  ChatApiSuggestionsRoute: ChatApiSuggestionsRoute,
  ChatApiVoteRoute: ChatApiVoteRoute,
  ChatApiFilesUploadRoute: ChatApiFilesUploadRoute,
  ChatApiChatIdStreamRoute: ChatApiChatIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
